/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Evolved
 */
public class kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form kuis2
     */
    public kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        brg4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brg2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        brg3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        brg1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dskn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Harga barang 4");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 140, 14);

        brg4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg4ActionPerformed(evt);
            }
        });
        getContentPane().add(brg4);
        brg4.setBounds(180, 140, 110, 30);

        jLabel2.setText("Harga barang 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 150, 14);

        brg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brg2ActionPerformed(evt);
            }
        });
        getContentPane().add(brg2);
        brg2.setBounds(180, 80, 110, 30);

        jLabel3.setText("Harga barang 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 150, 14);
        getContentPane().add(brg3);
        brg3.setBounds(180, 110, 110, 30);

        jLabel4.setText("Harga barang 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 50, 140, 14);
        getContentPane().add(brg1);
        brg1.setBounds(180, 50, 110, 30);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 150, 14);

        dskn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsknActionPerformed(evt);
            }
        });
        getContentPane().add(dskn);
        dskn.setBounds(180, 170, 110, 30);

        jLabel6.setText("Pembayaran");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 10, 80, 14);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(55, 220, 80, 23);

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(143, 220, 80, 23);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(233, 220, 80, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane2.setViewportView(TA);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 260, 370, 140);

        setBounds(0, 0, 416, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void brg4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg4ActionPerformed

    private void dsknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsknActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsknActionPerformed

    private void brg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brg2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int barang1 = Integer.parseInt(brg1.getText());
        int barang2 = Integer.parseInt(brg2.getText());
        int barang3 = Integer.parseInt(brg3.getText());
        int barang4 = Integer.parseInt(brg4.getText());
        int diskon = Integer.parseInt(dskn.getText());
        
        int TH = barang1 + barang2 + barang3 + barang4;
        int TB = TH*diskon/100;
        
        TA.setText("Harga Barang 1 : "+barang1+"\nHarga Barang 2 : "+barang2+"\nHarga Barang 3 : "+barang3+"\nHarga Barang 4 : "+barang4+"\nDiskon : "+diskon+
                "\nTotal Harga : "+TH+"\nTotal Bayar : "+TB);
        
 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TA.setText("");
        brg1.setText("");
        brg2.setText("");
        brg3.setText("");
        brg4.setText("");
        dskn.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField brg1;
    private javax.swing.JTextField brg2;
    private javax.swing.JTextField brg3;
    private javax.swing.JTextField brg4;
    private javax.swing.JTextField dskn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
